// Actionable insights — Demo Brief §5.

export const INSIGHTS = [
  {
    id: 'AI1',
    title: 'Ibrutinib AF and bleeding events driving switch conversations to Brukinsa',
    priority: 'High',
    lpRefs: ['LP1'], moRefs: ['MO1'],
    recurrence: 4,
    recency: '2026-06',
    summary: 'Community hematologists are increasingly encountering atrial fibrillation and bleeding events in ibrutinib-treated CLL patients, triggering active switch discussions. Cardiologists are now alerting hematology colleagues, and patients are asking why they remain on ibrutinib after a cardiac event.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community hematologist', location: 'Chicago, IL', quote: 'My cardiologist called me last week about a patient — she wanted to know if there was a safer BTK option. That is the first time that has happened.', date: '2026-06-08' },
      { type: 'MSL interaction', role: 'CLL patient advocate', location: 'Boston, MA', quote: 'Patients are asking why they are still on ibrutinib after an atrial fibrillation episode. They have read about the ALPINE data.', date: '2026-06-14' },
      { type: 'Congress debrief', role: 'Hematology-oncology MSL', location: 'EHA 2026', quote: 'The AF safety signal was cited in at least four separate sessions. Brukinsa was the named alternative in each case.', date: '2026-06-15' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.91,
    provenance: 'synthesized',
  },
  {
    id: 'AI2',
    title: 'CLL community oncologists unaware Brukinsa is a first-line option',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 3,
    recency: '2026-05',
    summary: 'Community hematology-oncology practices are defaulting to ibrutinib monotherapy or BR in CLL first line. Zanubrutinib as a first-line CLL option is not on the decision radar outside WM and MCL specialist community.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community hem-onc', location: 'Nashville, TN', quote: 'I use Brukinsa for MCL and WM. I did not know it was approved first-line for CLL. That changes things.', date: '2026-05-19' },
      { type: 'Med Info query', role: 'Community oncologist', location: 'Phoenix, AZ', quote: 'Asked for the approved indications list — confirmed they were only aware of the R/R setting.', date: '2026-05-26' },
      { type: 'Ad board', role: 'Community hem-onc director', location: 'Atlanta, GA', quote: 'Our default is still ibrutinib or BR for CLL first-line. Nobody has briefed us on Brukinsa here.', date: '2026-05-12' },
    ],
    status: 'Validated',
    confidenceScore: 0.86,
    provenance: 'synthesized',
  },
  {
    id: 'AI3',
    title: 'Tislelizumab not considered in esophageal SCC second-line — pembrolizumab reflex',
    priority: 'High',
    lpRefs: ['LP3'], moRefs: ['MO3'],
    recurrence: 3,
    recency: '2026-06',
    summary: 'Community GI oncologists are reflexively choosing pembrolizumab in esophageal SCC second-line. Tevimbra is invisible outside academic GI centres — same pattern as seen with Jemperli in endometrial cancer before targeted field engagement.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community GI oncologist', location: 'Dallas, TX', quote: 'Pembrolizumab is my default for esophageal SCC. I have not looked at other options since KEYNOTE-590.', date: '2026-06-03' },
      { type: 'Congress debrief', role: 'GI oncology MSL', location: 'ESMO GI 2026', quote: 'When we asked about second-line esophageal SCC options, pembrolizumab was named in 11 of 14 community conversations. Tislelizumab was not mentioned once.', date: '2026-06-18' },
      { type: 'Ad board', role: 'Academic GI oncologist', location: 'New York, NY', quote: 'RATIONALE-302 is compelling but nobody outside major centres is reading it. The community does not know this data exists.', date: '2026-06-07' },
    ],
    status: 'Validated',
    confidenceScore: 0.84,
    provenance: 'synthesized',
  },
  {
    id: 'AI4',
    title: 'Paolo Ghia divergence — time-limited BTK combination advocacy seeding European CLL network',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 2,
    recency: '2026-06',
    summary: 'Social monitoring has detected 2 LinkedIn posts and an EHA 2026 oral session question from Dr. Paolo Ghia (Milan) advocating for fixed-duration ibrutinib+venetoclax as superior to continuous zanubrutinib, citing GLOW and CAPTIVATE QoL data. His argument is seeding European CLL KOL opinion against continuous BTK monotherapy.',
    sourceInsights: [
      { type: 'Social monitoring', role: 'Dr. Paolo Ghia (LinkedIn)', location: 'Milan, Italy', quote: 'Fixed-duration BTK+ven gives our patients their life back. Continuous BTK therapy means continuous drug costs and continuous cardiovascular risk — even if reduced. GLOW 4-year data should change how we think about next-gen BTK.', date: '2026-06-09' },
      { type: 'Congress debrief', role: 'EHA 2026 session reporter', location: 'Milan, Italy', quote: 'Ghia planted a question in the ALPINE session Q&A asking whether the PFS advantage of zanubrutinib holds up against fixed-duration combinations. It generated the most heated exchange of the session.', date: '2026-06-14' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.88,
    provenance: 'synthesized',
  },
  {
    id: 'AI5',
    title: 'ALPINE OS data not reaching community hematologists — NEJM publication underexposed',
    priority: 'Medium',
    lpRefs: ['LP1', 'LP2'], moRefs: ['MO1', 'MO2'],
    recurrence: 2,
    recency: '2026-06',
    summary: 'ALPINE was published in the NEJM in 2023 showing OS HR 0.65 (p=0.0024) and AF rate 5.2% vs 13.3% — but community hematologists are not routinely citing this data. The publication is underexposed in community practice compared to academic centres.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community hematologist', location: 'Minneapolis, MN', quote: 'I was not aware ALPINE had OS data. I thought it was just PFS. Can you send me the NEJM paper?', date: '2026-06-21' },
      { type: 'MSL interaction', role: 'Community hem-onc', location: 'Denver, CO', quote: 'We get so many abstracts. If it was not in the ASCO plenary, we probably missed it. The ALPINE OS result would change my conversation with ibrutinib patients.', date: '2026-06-18' },
    ],
    status: 'Validated',
    confidenceScore: 0.79,
    provenance: 'synthesized',
  },
  {
    id: 'AI6',
    title: 'Tevimbra gastric HER2-negative — no clear champion KOL for 1L expansion narrative',
    priority: 'Medium',
    lpRefs: ['LP5'], moRefs: ['MO5'],
    recurrence: 1,
    recency: '2026-05',
    summary: 'No leading GI KOL is publicly championing tislelizumab as the preferred PD-1 choice in HER2-negative gastric first-line. The evidence gap means there is no one building the narrative — field intelligence identifies this as a white space requiring KOL identification and advisory engagement.',
    sourceInsights: [
      { type: 'Ad board', role: 'GI oncology advisory chair', location: 'Virtual', quote: 'If BeOne wants to own the HER2-negative gastric narrative, they need to find who is going to stand up and say that at ESMO. Right now nobody is doing it.', date: '2026-05-14' },
    ],
    status: 'Triaged',
    confidenceScore: 0.71,
    provenance: 'synthesized',
  },
  {
    id: 'AI7',
    title: 'BTK + venetoclax combination interest growing at EHA 2026 — physicians asking about Brukinsa+ven data',
    priority: 'Medium',
    lpRefs: ['LP4'], moRefs: ['MO4'],
    recurrence: 2,
    recency: '2026-06',
    summary: 'Multiple EHA 2026 session reports cite growing KOL interest in zanubrutinib + venetoclax combinations. Physicians are asking about MANIFEST-2 data and timing of readouts. This is partly driven by Ghia divergence but also represents genuine scientific enthusiasm for the combination approach.',
    sourceInsights: [
      { type: 'Congress debrief', role: 'Hematology MSL', location: 'EHA 2026 Milan', quote: 'Three separate KOLs asked me about the Brukinsa+venetoclax combination data at EHA. They want to know when the Phase III results are coming.', date: '2026-06-14' },
      { type: 'MSL interaction', role: 'Academic CLL specialist', location: 'Houston, TX', quote: 'The combination data will be what decides the next 5 years of CLL treatment. I am watching MANIFEST-2 closely. If zanubrutinib+ven shows what I think it will, the fixed-duration argument gets much more interesting.', date: '2026-06-22' },
    ],
    status: 'Validated',
    confidenceScore: 0.77,
    provenance: 'synthesized',
  },
];
